yolo_model:

  config_file:
    name: yolov3-tiny.cfg
  weight_file:
  # ---------------------------------- Change Here For Weight File --------------------------
    name: yolov3-tiny_210000.weights
  # -----------------------------------------------------------------------------------------
  threshold:
    value: 0.3
  detection_classes:
    names:
  # ---------------------------------- Change Here For Sorts --------------------------------
      - corn
      - corn_fruit
      - cucumber
      - cucumber_fruit
      - rice
      - watermelon
      - wheat
  # -----------------------------------------------------------------------------------------
